title: Wan Nur Shafiqah
logo: /images/photo_2024-07-31_06-17-14.jpg
description: Passionate Fresh Graduate in Statistics | Aspiring Data Analyst | Ready to Make an Impact in the Data Industry
theme: jekyll-theme-architect
